In [104]:
import pandas as pd
pd.__version__

'0.23.4'

In [105]:
import numpy as np

In [106]:
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [107]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [108]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [109]:
data[1]

0.5

In [110]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [111]:
data = pd.Series([0.25,0.5,0.75,1.0],
                index = ['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [112]:
data['b']

0.5

In [113]:
data = pd.Series([0.25,0.5,0.75,1.0],
                index = [2,5,3,7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [114]:
data[5]

0.5

In [115]:
population_dict = {'California':38332521,
                  'Texas':234234234,
                  'New York':34534534,
                  'Florida':3242343,
                  'Illinois':2342234324}
population = pd.Series(population_dict)
population

California      38332521
Texas          234234234
New York        34534534
Florida          3242343
Illinois      2342234324
dtype: int64

In [116]:
population['California':'Illinois']

California      38332521
Texas          234234234
New York        34534534
Florida          3242343
Illinois      2342234324
dtype: int64

In [117]:
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [118]:
pd.Series(5,index=[100,200,30])

100    5
200    5
30     5
dtype: int64

In [119]:
pd.Series({2:'a',1:'b',3:'c'})

2    a
1    b
3    c
dtype: object

In [120]:
pd.Series({2:'a',1:'b',3:'c'},index=[3,2])

3    c
2    a
dtype: object

In [121]:
area_dict = {'California':423967,'Texas':695662,'New York':141297,'Florida':170312,'Illinois':149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [122]:
states = pd.DataFrame({'population':population,
                      'area':area})
states

population    area
California    38332521  423967
Texas        234234234  695662
New York      34534534  141297
Florida        3242343  170312
Illinois    2342234324  149995

In [123]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [124]:
states.columns

Index(['population', 'area'], dtype='object')

In [125]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [126]:
states['California']

KeyError: 'California'

In [127]:
pd.DataFrame(population,columns=['population'])

population
California    38332521
Texas        234234234
New York      34534534
Florida        3242343
Illinois    2342234324

In [128]:
pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [129]:
data = [{'a':i,'b':2*i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [130]:
pd.DataFrame(np.random.rand(3,2),
            columns=['foo','bar'],
            index=['a','b','c'])

foo       bar
a  0.199392  0.531775
b  0.077960  0.832298
c  0.175556  0.776787

In [131]:
A = np.zeros(3,dtype=[('A','i8'),('B','f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [132]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [133]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [134]:
ind[1]

3

In [135]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [136]:
print(ind.size,ind.shape,ind.ndim,ind.dtype)

5 (5,) 1 int64


In [137]:
ind[0] = 0

TypeError: Index does not support mutable operations

In [ ]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [ ]:
indA & indB #交集

In [ ]:
indA | indB

In [ ]:
indA ^ indB

In [ ]:
data = pd.Series([0.25,0.5,.75,1.],
                index=['a','b','c','d'])
data

In [ ]:
data['b']

In [ ]:
'a' in data

In [ ]:
data.keys()

In [ ]:
data.index

In [ ]:
data.values

In [ ]:
list(data.items())

In [ ]:
data['e'] = 1.25
data

In [ ]:
data['a':'c']

In [ ]:
data[0:2]

In [ ]:
data[(data > 0.3) & (data < .8)]

In [ ]:
data[['a','e']]

In [ ]:
data = pd.Series(['a','b','c'],index=[1,3,5])
data

In [ ]:
data[1]

In [ ]:
data[1:3]

In [ ]:
data.loc[1] #显式索引

In [ ]:
data.loc[1:3]

In [ ]:
data.iloc[1] #隐式索引

In [ ]:
data.iloc[1:3]

In [ ]:
area

In [ ]:
population

In [ ]:
data = pd.DataFrame({'area':area,'pop':population})
data

In [ ]:
data['area']

In [ ]:
data.area

In [ ]:
data.area is data['area']

In [ ]:
data.pop is data['pop'] #前面的pop是dataframe的方法

In [ ]:
data['density'] = data['pop'] /data['area']
data

In [ ]:
data.values

In [ ]:
data.T

In [ ]:
data.values[0]

In [ ]:
data['area']

In [ ]:
data.iloc[:3,:2]

In [ ]:
data.loc[:'New York',:'pop']

In [ ]:
data.ix[:3,:'pop']

In [ ]:
data.loc[data.density > 100,['pop','density']]

In [ ]:
data.iloc[0,2] = 90
data

In [ ]:
data['Florida':'Illinois']

In [ ]:
data[1:3]

In [ ]:
data[data.density > 100]

In [ ]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

In [ ]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),
                 columns=['A','B','C','D'])
df

In [ ]:
np.exp(ser)

In [ ]:
np.sin(df*np.pi / 4)

In [ ]:
area = pd.Series({'Alaska':1723337,'Texas':695662,
                 'California':423967},name='area')
population = pd.Series({'California':38332521,'Texas':26448193,
                       'New York':19651127},name='population')

In [138]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [139]:
population /area

California       90.413926
Texas           336.706955
New York        244.410950
Florida          19.037666
Illinois      15615.416007
dtype: float64

In [140]:
area.index | population.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [141]:
A = pd.Series([2,4,6],index=[0,1,2])
B = pd.Series([1,3,5],index=[1,2,3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [142]:
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [143]:
A = pd.DataFrame(rng.randint(0,20,(2,2)),
                columns=list('AB'))
A

A   B
0  13  17
1   8   1

In [144]:
B = pd.DataFrame(rng.randint(0,10,(3,3)),
                columns=list('BAC'))
B

B  A  C
0  3  6  7
1  2  0  3
2  1  7  3

In [145]:
A + B

A     B   C
0  19.0  20.0 NaN
1   8.0   3.0 NaN
2   NaN   NaN NaN

In [146]:
fill = A.stack().mean()
A.add(B,fill_value=fill)

A      B      C
0  19.00  20.00  16.75
1   8.00   3.00  12.75
2  16.75  10.75  12.75

In [147]:
A.stack()

0  A    13
   B    17
1  A     8
   B     1
dtype: int32

In [148]:
A = rng.randint(10,size=(3,4))
A

array([[1, 5, 5, 9],
       [3, 5, 1, 9],
       [1, 9, 3, 7]])

In [149]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 2,  0, -4,  0],
       [ 0,  4, -2, -2]])

In [150]:
df = pd.DataFrame(A,columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  2  0 -4  0
2  0  4 -2 -2

In [151]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -4  0  0  4
1 -2  0 -4  4
2 -8  0 -6 -2

In [152]:
halfrow = df.iloc[0,::2]
halfrow

Q    1
S    5
Name: 0, dtype: int32

In [153]:
df-halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  2.0 NaN -4.0 NaN
2  0.0 NaN -2.0 NaN

In [154]:
vals1 = np.array([1,None,3,4])
vals1

array([1, None, 3, 4], dtype=object)

In [155]:
for dtype in ['object','int']:
    print("dtype= ",dtype)
    %timeit np.arange(1E6,dtype=dtype).sum()
    print()

dtype=  object
87.5 ms ± 11.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype=  int
3.94 ms ± 406 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [156]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [157]:
vals2 = np.array([1,np.nan,3,4])
vals2.dtype

dtype('float64')

In [158]:
1+np.nan

nan

In [159]:
0 * np.nan

nan

In [160]:
vals2.sum(),vals2.min(),vals2.max()

C:\anaconda\lib\site-packages\numpy\core\_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
C:\anaconda\lib\site-packages\numpy\core\_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)


(nan, nan, nan)

In [161]:
np.nansum(vals2),np.nanmax(vals2),np.nanmin(vals2)

(8.0, 4.0, 1.0)

In [162]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [163]:
x = pd.Series(range(2),dtype=int)
x

0    0
1    1
dtype: int32

In [164]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [165]:
data = pd.Series([1,np.nan,'hello',None])

In [166]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [167]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [168]:
data.dropna()

0        1
2    hello
dtype: object

In [169]:
df = pd.DataFrame([[1,np.nan,2],
                  [2,3,5],
                  [np.nan,4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [170]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [171]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [172]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [173]:
df.dropna(axis=1,how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [174]:
df.dropna(axis='rows',thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [175]:
data = pd.Series([1,np.nan,2,None,3],index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [176]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [177]:
data.fillna(method='ffill') #从前往后填充 forward-fill

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [178]:
data.fillna(method='bfill') #从后往前填充 back-fill

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [179]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [180]:
df.fillna(method='ffill',axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [181]:
index = [('California',2000),('California',2010),
        ('New York',2000),('New York',2010),
        ('Texas',2000),('Texas',2010)]
populations = [33871648,37253956,
              18976457,19378102,
              20851820,25145561]
pop = pd.Series(populations,index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [182]:
pop[('California',2010):('Texas',2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [183]:
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [184]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [185]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [186]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [187]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [188]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [189]:
pop_df = pd.DataFrame({'total':pop,
                      'under18':[9267089,9284094,
                                4687374,4318033,
                                5906301,6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [190]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [191]:
df = pd.DataFrame(np.random.rand(4,2),
                 index=[['a','a','b','b'],[1,2,1,2]],
                 columns=['data1','data2'])
df

data1     data2
a 1  0.012386  0.431119
  2  0.904095  0.916943
b 1  0.877468  0.451899
  2  0.904491  0.348967

In [192]:
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [193]:
data = {('California',2000):33871648,('California',2010):37253956,
        ('New York',2000):18976457,('New York',2010):19378102,
        ('Texas',2000):20851820,('Texas',2010):25145561}
pd.Series(data)

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [194]:
pd.MultiIndex.from_arrays([['a','a','b','b'],[1,2,1,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [195]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2)])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [196]:
pd.MultiIndex(levels=[['a','b'],[1,2]],
             labels=[[0,0,1,1],[0,1,0,1]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [197]:
pop.index.names=['state','year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [198]:
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],
                                  names=['year','visit'])
columns = pd.MultiIndex.from_product([['Bob','Guido','Sue'],['HR','Temp']],
                                    names=['subject','type'])
#模拟数据
data= np.round(np.random.randn(4,6),1)
data[:,::2] *= 10
data += 37

#创建DataFrame
health_data = pd.DataFrame(data,index=index,columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.0  36.4  50.0  36.6  20.0  36.5
     2      37.0  36.1  30.0  36.1  43.0  36.0
2014 1      42.0  38.1  29.0  38.0  33.0  37.2
     2      35.0  37.4  30.0  37.9  35.0  37.5

In [199]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      50.0  36.6
     2      30.0  36.1
2014 1      29.0  38.0
     2      30.0  37.9

In [200]:
health_data.unstack()

subject   Bob                   Guido                     Sue              \
type       HR        Temp          HR        Temp          HR        Temp   
visit       1     2     1     2     1     2     1     2     1     2     1   
year                                                                        
2013     36.0  37.0  36.4  36.1  50.0  30.0  36.6  36.1  20.0  43.0  36.5   
2014     42.0  35.0  38.1  37.4  29.0  30.0  38.0  37.9  33.0  35.0  37.2   

subject        
type           
visit       2  
year           
2013     36.0  
2014     37.5

In [201]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [202]:
pop['California',2000]

33871648

In [203]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [204]:
pop.loc['California':'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [205]:
pop[:,2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [206]:
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [207]:
pop[['California','Texas']]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

In [208]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.0  36.4  50.0  36.6  20.0  36.5
     2      37.0  36.1  30.0  36.1  43.0  36.0
2014 1      42.0  38.1  29.0  38.0  33.0  37.2
     2      35.0  37.4  30.0  37.9  35.0  37.5

In [209]:
health_data['Guido','HR']

year  visit
2013  1        50.0
      2        30.0
2014  1        29.0
      2        30.0
Name: (Guido, HR), dtype: float64

In [210]:
health_data.iloc[:2,:2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      36.0  36.4
     2      37.0  36.1

In [211]:
health_data.loc[:,('Bob','HR')]

year  visit
2013  1        36.0
      2        37.0
2014  1        42.0
      2        35.0
Name: (Bob, HR), dtype: float64

In [212]:
idx = pd.IndexSlice
health_data.loc[idx[:,1],idx[:,'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      36.0  50.0  20.0
2014 1      42.0  29.0  33.0

In [213]:
index = pd.MultiIndex.from_product([['a','c','b'],[1,2]])
data = pd.Series(np.random.rand(6),index=index)
data.index.names= ['char','int']
data

char  int
a     1      0.940276
      2      0.426018
c     1      0.243330
      2      0.117451
b     1      0.323471
      2      0.690554
dtype: float64

In [214]:
try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [215]:
data =data.sort_index()
data

char  int
a     1      0.940276
      2      0.426018
b     1      0.323471
      2      0.690554
c     1      0.243330
      2      0.117451
dtype: float64

In [216]:
data['a':'b']

char  int
a     1      0.940276
      2      0.426018
b     1      0.323471
      2      0.690554
dtype: float64

In [217]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [218]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [219]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [220]:
pop_flat = pop.reset_index(name='population')
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [221]:
pop_flat.set_index(['state','year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [222]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.0  36.4  50.0  36.6  20.0  36.5
     2      37.0  36.1  30.0  36.1  43.0  36.0
2014 1      42.0  38.1  29.0  38.0  33.0  37.2
     2      35.0  37.4  30.0  37.9  35.0  37.5

In [223]:
data_mean = health_data.mean(level='year')
data_mean

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     36.5  36.25  40.0  36.35  31.5  36.25
2014     38.5  37.75  29.5  37.95  34.0  37.35

In [224]:
data_mean.mean(axis=1,level='type')

type    HR       Temp
year                 
2013  36.0  36.283333
2014  34.0  37.683333

In [225]:
def make_df(cols,ind):
    """一个简单的DataFrame"""
    data = {c:[str(c) + str(i) for i in ind] for c in cols}
    return pd.DataFrame(data,ind)

make_df('ABC',range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [226]:
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [227]:
x = [[1,2],
    [3,4]]
np.concatenate([x,x],axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [228]:
ser1 = pd.Series(['A','B','C'],index=[1,2,3])
ser2 = pd.Series(['D','E','F'],index=[4,5,6])
pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [229]:
df1 = make_df('AB',[1,2])
df2 = make_df('AB',[3,4])
print(df1)
print(df2)
print(pd.concat([df1,df2]))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [230]:
df3 = make_df('AB',[0,1])
df4 = make_df('CD',[0,1])
print(df3)
print(df4)
print(pd.concat([df3,df4],axis=1))

    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


In [231]:
x = make_df('AB',[0,1])
y = make_df('AB',[2,3])
y.index=x.index #复制索引
print(x)
print(y)
print(pd.concat([x,y]))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


In [232]:
try:
    pd.concat([x,y],verify_integrity=True)
except ValueError as e:
    print('ValueError :',e)

ValueError : Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


In [233]:
print(x)
print(y)
print(pd.concat([x,y],ignore_index=True))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3


In [234]:
print(x)
print(y)
print(pd.concat([x,y],keys=['x','y']))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3


In [235]:
df5 = make_df('ABC',[1,2])
df6 = make_df('BCD',[3,4])
print(df5)
print(df6)
print(pd.concat([df5,df6]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


C:\anaconda\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """


In [236]:
print(df5)
print(df6)
print(pd.concat([df5,df6],join='inner')) #交集合并

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [237]:
print(df5)
print(df6)
print(pd.concat([df5,df6],join_axes=[df5.columns]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4


In [238]:
print(df5)
print(df6)
print(df5.append(df6))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


C:\anaconda\lib\site-packages\pandas\core\frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)
